{% set name = "hpp-fcl" %}
{% set zipname = "coal" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ name }}/releases/download/v{{ version }}/{{ zipname }}-{{ version }}.tar.gz
  sha256: 6a9cbd4684e907fd16577e5227fbace06ac15ca861c0846dfe5bc81e565fb1e7

build:
  noarch: generic
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - python
    - numpy
    - coal
  run:
    - coal

test:
  imports:
    - hppfcl
  commands:
    - if not exist %LIBRARY_PREFIX%\\lib\\cmake\\hpp-fcl\\hpp-fclConfig.cmake exit 1  # [win]
    - test -f $PREFIX/lib/cmake/hpp-fcl/hpp-fclConfig.cmake  # [unix]

about:
  home: https://github.com/humanoid-path-planner/hpp-fcl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An extension of the Flexible Collision Library
  dev_url: https://github.com/humanoid-path-planner/hpp-fcl

extra:
  recipe-maintainers:
    - jorisv
    - jcarpent
    - wolfv
    - ymontmarin
