{% set name = "hpp-fcl" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # TODO use the archive when hpp-fcl 3 is released
  git_url: https://github.com/jorisv/hpp-fcl
  git_rev: topic/install-compatibility-layer

build:
  number: 8
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - clang  # [win]
    - ninja
    - doxygen
  host:
    - python
    - numpy
    - coal
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - coal

test:
  imports:
    - hppfcl
  commands:
    - if not exist %LIBRARY_PREFIX%\\lib\\cmake\\hpp-fcl\\hpp-fclConfig.cmake exit 1  # [win]
    - test -f $PREFIX/lib/cmake/hpp-fcl/hpp-fclConfig.cmake  # [unix]

about:
  home: https://github.com/humanoid-path-planner/hpp-fcl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An extension of the Flexible Collision Library
  dev_url: https://github.com/humanoid-path-planner/hpp-fcl

extra:
  recipe-maintainers:
    - jorisv
    - jcarpent
    - wolfv
    - ymontmarin
