{% set name = "hpp-fcl" %}
{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ name }}/releases/download/v{{ version }}/hpp-fcl-{{ version }}.tar.gz
  sha256: 2b6f2911318627b368f6504e0df01aef2d2ab622e3f4f85ecba7f4bdca852296

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - cmake
    - clang  # [win]
    - make  # [not win]
    - doxygen
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pylatexenc  # [not win]
    - lxml  # [not win]
  host:
    - eigen
    - boost
    - python
    - eigenpy
    - assimp
    - octomap
    - numpy
    - pylatexenc  # [not win]
    - lxml  # [not win]
    - qhull
  run:
    - assimp
    - eigen
    - octomap
    - boost
    - python
    - eigenpy
    - {{ pin_compatible('numpy') }}
    - qhull

test:
  requires:
    - pkg-config
  imports:
    - hppfcl
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/humanoid-path-planner/hpp-fcl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An extension of the Flexible Collision Library
  dev_url: https://github.com/humanoid-path-planner/hpp-fcl

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - ymontmarin
