{% set name = "hpp-fcl" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ name }}/releases/download/v{{ version }}/hpp-fcl-{{ version }}.tar.gz
  sha256: 4e1434dee200e13a6d27ab546e2af255e3f4c76d363269963b9a9dc137ea3528

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}


requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - cmake
    - clang  # [win]
    - make  # [not win]
  host:
    - eigen
    - boost
    - python
    - eigenpy
    - assimp
    - octomap
  run:
    - assimp
    - eigen
    - octomap
    - boost
    - python
    - eigenpy

test:
  requires:
    - pkg-config
  imports:
    - hppfcl
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/humanoid-path-planner/hpp-fcl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An extension of the Flexible Collision Library
  dev_url: https://github.com/humanoid-path-planner/hpp-fcl

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
