{% set name = "hpp-fcl" %}
{% set zipname = "coal" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ name }}/releases/download/v{{ version }}/{{ zipname }}-{{ version }}.tar.gz
  sha256: b9609301baefbbf45b4e0f80865abc2b2dcbb69c323a55b0cd95f141959c478c

build:
  noarch: python
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - python 3.10
    - numpy
    - coal {{ version }}
  run:
    # libcoal is run exported but not coal-python
    - coal {{ version }}
    - python >={{ python_min }}
    - __unix  # [unix]
    - __win   # [win]

test:
  imports:
    - hppfcl
  commands:
    - if not exist %LIBRARY_PREFIX%\\lib\\cmake\\hpp-fcl\\hpp-fclConfig.cmake exit 1  # [win]
    - test -f $PREFIX/lib/cmake/hpp-fcl/hpp-fclConfig.cmake  # [unix]

about:
  home: https://github.com/humanoid-path-planner/hpp-fcl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An extension of the Flexible Collision Library
  dev_url: https://github.com/humanoid-path-planner/hpp-fcl

extra:
  recipe-maintainers:
    - jorisv
    - jcarpent
    - wolfv
    - ymontmarin
